version: "3.9"

services:

  webserver:
    image: nginx:alpine
    container_name: ${APP}-webserver
    working_dir: /mnt/api
    volumes:
      - ./api:/mnt/api
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    container_name: ${APP}-php-fpm
    working_dir: /mnt/api/
    volumes:
      - ./api:/mnt/api/
      - ./docker/php-fpm/php-ini-overrides.local.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
      - .env:/mnt/api/.env
      - ./docs/tests/test.csv:/tmp/test.csv
      - ./docs/tests/9c4021a8-5ab9-42c8-8395-7113907ad457.zip:/tmp/9c4021a8-5ab9-42c8-8395-7113907ad457.zip
    environment:
      ALPINE_VERSION: ${ALPINE_VERSION}
      COMPOSER_VERSION: ${COMPOSER_VERSION}
    ports:
      - "8000:8000"

  database:
    image: mysql:8.0.32
    container_name: ${APP}-database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./data/volumes/mysql:/var/lib/mysql
      - ./docs/sql/dump.sql:/tmp/dump.sql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${APP}-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq/log/:/var/log/rabbitmq
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia
